# vim:fileencoding=utf-8:foldmethod=marker

font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0
term xterm-24bit
macos_thicken_font 0.2
macos_option_as_alt yes
foreground #00FF66
background #171717
adjust_column_width 90%
